const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createServer}=require('node:http');
const fs=require('node:fs/promises');
const path=require('node:path');
const {chromium}=require('../.test-tools/node_modules/playwright');
test('confirmar recebe, bloqueia edição, contabiliza saídas e fecha o caixa',async()=>{
 const root=path.resolve(__dirname,'..','front-end');
 const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(file)]||'application/octet-stream')+'; charset=utf-8');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 let browser;
 try{
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1536,height:1100},serviceWorkers:'block'});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin)return route.abort();if(url.pathname==='/js/config.js')return route.fulfill({contentType:'text/javascript',body:'window.APP_CONFIG={demoAdminPin:"test",storeName:"Snoop"};'});return route.continue();});
  await page.addInitScript(()=>{if(localStorage.getItem('fixture'))return;localStorage.setItem('fixture','yes');sessionStorage.setItem('snoop_admin_session_v1','authenticated');localStorage.setItem('snoop_products_v1',JSON.stringify(['Produto teste','Produto zero A','Produto zero B','Produto zero C','Produto zero D'].map((name,index)=>({id:index?'zero-'+index:'produto',name,description:'Teste',price:10,category:'Teste',image:'assets/pwa/zeus.png',available:true}))));localStorage.setItem('snoop_orders_v1',JSON.stringify(['Dinheiro','Pix','Cartão na entrega','Pix'].map((payment,i)=>({id:`10000000-0000-0000-0000-00000000000${i+1}`,code:`TESTE${i+1}`,customerName:'Cliente teste',status:i===3?'cancelled':'pending',trustedTotal:[40,60,30,20][i],clientTotal:999,address:'Venda presencial',payment,items:[{productId:'produto',name:'Produto teste',quantity:1,unitPrice:[40,60,30,20][i],subtotal:[40,60,30,20][i]}],createdAt:new Date(Date.now()-86400000).toISOString()}))));});
  await page.goto(origin+'/admin.html');
  await page.waitForFunction(()=>document.querySelector('#modeTitle').textContent==='Caixa fechado');
  assert.equal(await page.locator('#cashStatus').getAttribute('class'),'mode-indicator is-closed');
  assert.equal(await page.locator('#cashStatus > span').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 93, 93)');
  await page.locator('[data-view=cashClosing]').click();
  await page.locator('#registerOpenForm input').fill('100');await page.locator('#registerOpenForm button').click();
  await page.locator('#registerContent').waitFor({state:'visible'});
  await page.waitForFunction(()=>document.querySelector('#modeTitle').textContent==='Caixa aberto');
  assert.match(await page.locator('#modeText').innerText(),/^Aberto às \d{2}:\d{2}$/);
  assert.equal(await page.locator('#cashStatus > span').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(81, 216, 138)');
  assert.match(await page.locator('#registerTotals').innerText(),/100,00/);
  assert.equal(await page.locator('#registerTotals').getByText('Automático').count(),0);
  await page.locator('[data-total-detail=opening]').click();assert.match(await page.locator('[data-total-detail-panel=opening]').innerText(),/Valor do início do expediente/);
  await page.locator('#registerEntryCard h3').click();assert.equal(await page.locator('[data-total-detail-panel=opening]').isVisible(),false,'clique fora fecha os detalhes');
  await page.locator('[data-total-detail=opening]').click();
  await page.locator('[data-close-total-detail]').click();
  await page.locator('#registerPendingTitle').click();
  assert.equal(await page.locator('#registerMovementForm option[value=receipt]').count(),0);
  assert.deepEqual(await page.locator('#registerSalesMethods strong').evaluateAll(els=>els.map(el=>getComputedStyle(el).color)),['rgb(255, 255, 255)','rgb(255, 255, 255)','rgb(255, 255, 255)']);
  assert.equal(await page.locator('#registerCloseForm button[type=submit]').isDisabled(),true);
  await page.locator('[data-pending-order="10000000-0000-0000-0000-000000000001"][data-order-status=confirmed]').click();
  await page.locator('[data-pending-order="10000000-0000-0000-0000-000000000001"]').first().waitFor({state:'detached'});
  await page.evaluate(()=>{const rows=JSON.parse(localStorage.getItem('snoop_orders_v1'));rows.push({...rows[0],id:'cancel-in-closing',code:'CANCELAR',status:'pending'});localStorage.setItem('snoop_orders_v1',JSON.stringify(rows));AdminCashClosing.open();});
  await page.locator('[data-pending-order="cancel-in-closing"][data-order-status=cancelled]').click();
  await page.locator('[data-pending-order="cancel-in-closing"]').first().waitFor({state:'detached'});
  assert.match(await page.evaluate(async()=>{try{await StoreAPI.updateOrderStatus('cancel-in-closing','confirmed');return 'aceito';}catch(e){return e.message;}}),/cancelado não pode/);
  await page.locator('[data-view=orders]').click();
  const firstOrder=page.locator('#ordersList .order-row').first();await firstOrder.locator('[data-expand]').click();assert.equal(await firstOrder.locator('.order-details').isVisible(),true);await page.locator('#ordersView .panel-heading h2').click();assert.equal(await firstOrder.locator('.order-details').isVisible(),false,'clique fora fecha detalhes do pedido');
  for(let i=2;i<=3;i++) {await page.locator(`#ordersList [data-id="10000000-0000-0000-0000-00000000000${i}"] [data-status=confirmed]`).click();await page.locator(`#ordersList [data-id="10000000-0000-0000-0000-00000000000${i}"]`).waitFor({state:'detached'});}
  await page.locator('[data-order-filter=confirmed]').click();
  assert.equal(await page.locator('#confirmedOrdersList [data-status]').count(),0);
  const rejection=await page.evaluate(async()=>{try{await StoreAPI.updateOrderStatus('10000000-0000-0000-0000-000000000001','cancelled');return 'aceito';}catch(e){return e.message;}});
  assert.match(rejection,/não pode ser alterado/);
  await page.evaluate(()=>StoreAPI.updateOrderStatus('10000000-0000-0000-0000-000000000001','confirmed'));
  await page.locator('[data-view=cashClosing]').click();
  await page.locator('#registerContent').waitFor({state:'visible'});
  assert.match(await page.locator('#registerPendingTitle').innerText(),/Nenhum/);
  assert.equal(await page.locator('#registerCloseForm button[type=submit]').isDisabled(),true,'valor conferido é obrigatório');
  await page.locator('[data-total-detail=sales]').click();
  await page.waitForFunction(()=>document.querySelector('[data-total-detail-panel=sales]').textContent.includes('Produto teste'));
  assert.match(await page.locator('[data-total-detail-panel=sales]').innerText(),/Cliente teste/);
  assert.equal(await page.locator('[data-verify]').count(),0);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('snoop_register_v2')).movements.filter(m=>m.kind==='receipt').length),3);
  assert.equal(await page.locator('[data-view=expenses],#expensesView,#expenseForm').count(),0);
  await page.locator('#registerMovementForm [name=kind]').selectOption('expense');
  const movementAmount=page.locator('#registerMovementForm [name=amount]');await movementAmount.fill('10');await movementAmount.focus();await page.mouse.wheel(0,120);assert.equal(await movementAmount.inputValue(),'10','rolagem não altera campos numéricos');await movementAmount.press('ArrowUp');assert.equal(await movementAmount.inputValue(),'10','teclas de incremento não alteram campos numéricos');
  await page.locator('#registerMovementForm [name=description]').fill('Compra de embalagens');await page.locator('#registerMovementForm [name=amount]').fill('25');await page.locator('#registerMovementForm [name=method]').selectOption('cash');await page.locator('#registerMovementForm button[type=submit]').click();
  await page.locator('#feedbackDialog').waitFor({state:'visible'});assert.equal(await page.locator('#feedbackDialog').getAttribute('data-tone'),'warning');await page.locator('#feedbackConfirm').click();
  await page.waitForFunction(()=>document.querySelector('#registerMovementForm [name=amount]').value==='');
  await page.waitForFunction(()=>document.querySelector('#registerSalesTotal').textContent.includes('205,00'));
  await page.locator('[data-view=dashboard]').click();
  await page.waitForFunction(()=>document.querySelector('#dashOutcome').textContent.includes('25,00'));
  assert.equal(await page.locator('#dashOrdersTotal').innerText(),'5');
  assert.match(await page.locator('#dashOrdersStatus').innerText(),/3 confirmados · 2 cancelados/);
  assert.equal(await page.locator('.product-ranking-group').first().locator('.ranking-row').count(),3);
  assert.equal(await page.locator('.product-ranking-group.least .ranking-row').count(),2);
  assert.match(await page.locator('.product-ranking-group.least').innerText(),/0 un\./);
  assert.equal(await page.locator('.product-ranking-group').first().locator('.ranking-row').first().locator('strong').evaluate(el=>getComputedStyle(el).color),'rgb(81, 216, 138)');
  assert.equal(await page.locator('.product-ranking-group.least .ranking-row').first().locator('strong').evaluate(el=>getComputedStyle(el).color),'rgb(255, 122, 122)');
  assert.equal(await page.locator('.product-ranking-group:not(.least) .ranking-row.no-sales').first().locator('strong').evaluate(el=>getComputedStyle(el).color),'rgb(81, 216, 138)');
  const promotionTarget=await page.locator('[data-promote-product]').first().getAttribute('data-promote-product');
  await page.locator('[data-promote-product]').first().click();await page.locator('#promotionDialog').waitFor({state:'visible'});
  assert.match(await page.locator('#promotionOriginalPrice').innerText(),/10,00/);
  await page.locator('#promotionActive').check();await page.locator('#promotionForm [name=salePrice]').fill('7.50');await page.screenshot({path:'.test-tools/promotion-dialog.png',fullPage:false});await page.locator('#savePromotion').click();await page.locator('#promotionDialog').waitFor({state:'hidden'});
  const promotedProduct=await page.evaluate(id=>JSON.parse(localStorage.getItem('snoop_products_v1')).find(product=>product.id===id),promotionTarget);
  assert.equal(promotedProduct.price,10,'preço original preservado');assert.equal(promotedProduct.sale_price,7.5,'preço promocional salvo separadamente');
  const catalogPage=await context.newPage();await catalogPage.goto(origin+'/index.html');const promotedCard=catalogPage.locator(`[data-product-card="${promotionTarget}"]`);await promotedCard.waitFor();assert.match(await promotedCard.locator('.product-price s').innerText(),/10,00/);assert.match(await promotedCard.locator('.product-price span').innerText(),/7,50/);assert.equal(await promotedCard.locator('.promotion-discount').innerText(),'-25%');await promotedCard.locator('[data-add]').click();await catalogPage.locator('#purchaseForm .purchase-confirm').click();assert.match(await catalogPage.locator('#cartTotal').innerText(),/7,50/);await catalogPage.close();
  const promotionalOrder=await page.evaluate(id=>StoreAPI.createOrder({customerName:'Cliente promo',deliveryType:'Retirada',address:'',payment:'Pix',notes:'',clientTotal:7.5,items:[{productId:id,quantity:1,variant:'unit'}]}),promotionTarget);
  assert.equal(promotionalOrder.trustedTotal,7.5,'novo pedido usa o preço promocional');await page.evaluate(id=>StoreAPI.updateOrderStatus(id,'cancelled'),promotionalOrder.id);await page.waitForTimeout(500);
  const help=page.locator('.metric-help');assert.equal(await help.count(),4);
  await help.first().dispatchEvent('click');await page.locator('.dashboard-tooltip').waitFor({state:'visible'});
  assert.match(await page.locator('.dashboard-tooltip').innerText(),/dinheiro, Pix e cartão/);
  await page.keyboard.press('Escape');await page.locator('.dashboard-tooltip').waitFor({state:'hidden'});
  await help.nth(3).focus();await page.keyboard.press('Enter');
  assert.match(await page.locator('.dashboard-tooltip').innerText(),/confirmados/);
  await page.keyboard.press('Escape');await page.evaluate(()=>document.activeElement.blur());
  await page.setViewportSize({width:390,height:900});await help.first().scrollIntoViewIfNeeded();await page.waitForTimeout(300);
  await help.first().dispatchEvent('click');
  await page.locator('.dashboard-tooltip').waitFor({state:'visible'});
  const tip=await page.locator('.dashboard-tooltip').boundingBox();assert.ok(tip.x>=0&&tip.x+tip.width<=390);
  assert.equal(await page.locator('.dashboard-tooltip').isVisible(),true);
  await page.screenshot({path:'.test-tools/dashboard-help-mobile.png',fullPage:false});
  await page.locator('#dashboardView h2').click();await page.locator('.dashboard-tooltip').waitFor({state:'hidden'});
  await page.setViewportSize({width:1536,height:1100});
  await page.locator('[data-view=cashClosing]').click();await page.locator('#registerContent').waitFor({state:'visible'});
  assert.match(await page.locator('#registerSalesTotal').innerText(),/205,00/,'saldo inclui abertura e todas as vendas menos saídas');
  assert.match(await page.locator('#registerSalesMethods').innerText(),/40,00/);
  assert.match(await page.locator('#registerSalesMethods').innerText(),/60,00/);
  assert.match(await page.locator('#registerSalesMethods').innerText(),/30,00/);
  assert.notEqual(await page.locator('#registerSalesMethods strong').last().evaluate(el=>getComputedStyle(el).color),'rgb(255, 255, 255)');
  await page.screenshot({path:'.test-tools/register-desktop.png',fullPage:true});
  assert.equal(await page.locator('[name=counted_cash]').count(),1);
  await page.locator('#registerCloseForm [name=counted_cash]').fill('205');await page.locator('#registerCloseForm [name=counted_cash]').press('ArrowUp');
  assert.equal(await page.locator('#registerCloseForm [name=counted_cash]').inputValue(),'205');
  await page.locator('#registerCloseForm [name=counted_cash]').fill('180');
  assert.equal(await page.locator('#registerShortageAlert').isVisible(),true);
  assert.equal(await page.locator('#registerCloseForm [name=notes]').getAttribute('required'),'');
  await page.locator('#registerMissingMovement').click();
  assert.equal(await page.locator('#registerMovementForm [name=amount]').inputValue(),'25.00');
  await page.locator('#registerCloseForm [name=counted_cash]').fill('210');
  await page.locator('#registerCloseForm button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#cashClosingConfirm').textContent.includes('Deseja fechar o caixa mesmo assim'));
  assert.match(await page.locator('#cashClosingConfirm').innerText(),/Deseja fechar o caixa mesmo assim/);
  assert.equal(await page.locator('#saveCashClosing').innerText(),'Fechar mesmo assim');
  assert.equal(await page.locator('#cashClosingConfirm').evaluate(dialog=>{const box=dialog.getBoundingClientRect();return Math.abs(box.left+box.width/2-innerWidth/2)<2&&Math.abs(box.top+box.height/2-innerHeight/2)<2;}),true,'conferencia final centralizada');
  await page.mouse.click(8,8);await page.locator('#cashClosingConfirm').waitFor({state:'hidden'});
  await page.locator('#registerCloseForm [name=counted_cash]').fill('205');
  await page.locator('#registerCloseForm button[type=submit]').click();
  assert.match(await page.locator('#closingConfirmSummary').innerText(),/205,00/);
  assert.match(await page.locator('#closingConfirmSummary').innerText(),/Vendas em cartão/);await page.locator('#saveCashClosing').click();await page.locator('#cashClosingConfirm').waitFor({state:'hidden'});
  await page.locator('#registerOpening').waitFor({state:'visible'});assert.equal(await page.locator('#registerEntryCard').isVisible(),false);
  await page.waitForFunction(()=>document.querySelector('#modeTitle').textContent==='Caixa fechado');
  assert.equal(await page.locator('#cashStatus > span').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 93, 93)');
  await page.locator('[data-view=orders]').click();
  await page.waitForFunction(()=>document.querySelector('#confirmedBadge').textContent==='0');
  assert.equal(await page.locator('#confirmedOrdersList .order-row').count(),0,'confirmados do caixa encerrado saem do novo ciclo');
  assert.equal(await page.evaluate(()=>Object.values(JSON.parse(localStorage.getItem('snoop_register_v2')).orderStates).filter(order=>order.status==='confirmed').length),3,'pedidos anteriores continuam salvos');
  await page.reload();await page.locator('[data-view=cashClosing]').click();await page.locator('#registerOpening').waitFor({state:'visible'});
  await page.locator('.closing-history > summary').click();
  await page.locator('[data-report]').first().click();assert.match(await page.locator('#closingReportBody').innerText(),/205,00/);assert.match(await page.locator('#closingReportBody').innerText(),/Cartão/);assert.equal(await page.locator('#cashClosingReport').evaluate(dialog=>{const box=dialog.getBoundingClientRect();return Math.abs(box.left+box.width/2-innerWidth/2)<2&&Math.abs(box.top+box.height/2-innerHeight/2)<2;}),true,'relatorio de fechamento centralizado');await page.mouse.click(8,8);await page.locator('#cashClosingReport').waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('snoop_register_v2')).closings[0].expected_cash),205);
  await page.locator('#registerOpenForm input').fill('20');await page.locator('#registerOpenForm button').click();await page.locator('#registerContent').waitFor({state:'visible'});
  assert.match(await page.locator('#registerSalesTotal').innerText(),/20,00/,'novo caixa sem duplicar vendas');
  await page.locator('[data-view=orders]').click();await page.waitForFunction(()=>document.querySelector('#confirmedBadge').textContent==='0');
  assert.equal(await page.locator('#confirmedOrdersList .order-row').count(),0,'novo caixa começa sem confirmados do anterior');
  await page.locator('[data-view=cashClosing]').click();
  assert.match(await page.locator('#registerSalesTotal').innerText(),/20,00/);
  await page.locator('#registerCloseForm [name=counted_cash]').fill('20');await page.locator('#registerCloseForm button[type=submit]').click();await page.locator('#saveCashClosing').click();await page.locator('#cashClosingConfirm').waitFor({state:'hidden'});
  assert.equal(await page.locator('[data-report]').count(),2,'dois caixas preservados');
  for(const width of [390,768]){await page.setViewportSize({width,height:900});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`sem overflow em ${width}`);assert.ok((await page.locator('.admin-sidebar').boundingBox()).x<0,'menu recolhido no celular');await page.screenshot({path:`.test-tools/register-${width}.png`,fullPage:true});}
  await page.setViewportSize({width:1536,height:1100});await page.waitForTimeout(300);
  const catalogBefore=await page.evaluate(()=>localStorage.getItem('snoop_products_v1'));
  await page.locator('[data-view=control]').click();await page.locator('#openResetData').click();
  await page.locator('#resetDataForm [name=password]').fill('incorreta');await page.locator('#resetDataForm [name=confirmation]').fill('ZERAR');await page.locator('#confirmResetData').click();
  assert.equal(await page.locator('#resetDataDialog').isVisible(),true);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('snoop_register_v2')).closings.length),2);
  await page.locator('#resetDataForm [name=password]').fill('test');await page.locator('#confirmResetData').click();await page.locator('#resetDataDialog').waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>localStorage.getItem('snoop_products_v1')),catalogBefore);
  await page.locator('[data-view=cashClosing]').click();await page.locator('#registerOpening').waitFor({state:'visible'});assert.equal(await page.locator('[data-report]').count(),0);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('snoop_orders_v1')).length),0);
  // Só um caixa vazio também pode ser removido: não depende de pedidos/saídas.
  await page.locator('#registerOpenForm input').fill('0');await page.locator('#registerOpenForm button').click();await page.locator('#registerContent').waitFor({state:'visible'});
  await page.locator('[data-view=control]').click();await page.locator('#openResetData').click();await page.locator('#resetDataForm [name=password]').fill('test');await page.locator('#resetDataForm [name=confirmation]').fill('ZERAR');await page.locator('#confirmResetData').click();await page.locator('#resetDataDialog').waitFor({state:'hidden'});
  await page.locator('[data-view=cashClosing]').click();await page.locator('#registerOpening').waitFor({state:'visible'});
  assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
});
